### PR TITLE
Comments simplified

### PR DESCRIPTION
**Pull request by Robert-Krajcik**

### CODE REVIEW

**Comment by Robert-Krajcik** [comment]
This partially addresses #53 -- Remove Code duplication
By adding functions ins_cmts(), sel_cmts() and dsp_cmts() to utils.R
We can remove a lot of redundant code in comments handling.

**Comment by Robert-Krajcik** [comment]
Thanks for reviewing this, @AARON-CLARK 
I can update the function names, 
and look into the single quote issue on Monday

**Comment by Robert-Krajcik** [comment]
In many SQL implementations, doubling achieves the escaping you want:

_**insert_comment(input$select_pack, input$select_ver, values$name, values$role, gsub("'","''",input$mm_comment), cm_type = "mm")**_

And this seems to work!
image

**Comment by Robert-Krajcik** [comment]
Ready for  you to review again, @AARON-CLARK

**Review by AARON-CLARK — APPROVED** [review]
Looks great and tested successfully!

**Pull request merged**
