### PR TITLE
Fix versioning II

### PR DESCRIPTION
**Pull request by ghost**
Replacement for the Fix Versioning PR

- Updated all five SQL tables.
- All comments are specific to a package version.
-  Sidebar select inputs for package and version work.
-  Commented out values$mm_tab_redirect -- does not automatically go to main metrics tab.
-  Updated `timestamp()` function (used in comments table) to something MySQL or MariaDB would accept.
-  testing_metrics amAngularGauge value hardcoded to 0 for now.

### CODE REVIEW

**Comment by Robert-Krajcik** [comment]
With these changes, we will be able to work with multiple versions per package.

ToDo:
Update the community usage metrics reporting.
I want to be able to show **at least** 12 months of downloads from the date the version of interest was available,
not the last 365 days.

**Comment by Robert-Krajcik** [comment]
Some testing:
image

results in
image
and
image

non-existent packages or versions don't even make it to values$Total

Version 1.2.1 of janitor actually got an error message 
{"timestamp": "2020-09-24T11:51:19-0400", "log_lvl": "ERROR", "log_msg": "Error in extracting general info of the package janitor info Error in signalCondition(e): object 'e' not found__LF__", "app": "fileupload-webscraping"}
and was removed from values$New and became an "undiscovered" package

The total, of course, is the cumulative total packages + versions in the packageinfo table

Instead of this
```{r, eval=FALSE}
  values$Dup <- filter(values$Total,   values$Total$package %in% pkgs_db1$package & values$Total$version %in% pkgs_db1$version)
  values$New <- filter(values$Total, !(values$Total$package %in% pkgs_db1$package & values$Total$version %in% pkgs_db1$version))
```
dplyr joins work just fine
```{r, eval=FALSE}
  values$Dup <- inner_join(values$Total, pkgs_db1, by = c("package","version"))
  values$New <- anti_join( values$Total, pkgs_db1, by = c("package","version"))
```

**Comment by Robert-Krajcik** [comment]
This is about as far as I can get with it.
enhancements for collecting package info, maintenance metrics, and community usage metrics
will be part of another PR sometime in the near future.

@AARON-CLARK,  can you take a look at this, make sure I didn't forget something, let me know what you think?

**Comment by marlycormar** [comment]
Hi @Robert-Krajcik, I'll also try to take a look at this PR.

**Comment by marlycormar** [comment]
Hi @Robert-Krajcik, when I use the example dataset, I get the following issues:

- Although the uploaded file contains `dplyr` version `1.0.0`, the dropdown only shows the latest version, namely `1.0.2`.

- The DT package fails to load with error:
```
{"timestamp": "2020-09-28T17:39:42-0400", "log_lvl": "ERROR", "log_msg": "Error in uploading the general info
 of the package DT info Error: near __DBLQUOTE__DataTables__DBLQUOTE__: syntax error__LF__", "app":
 "fileupload-DB"}
```

**Comment by Robert-Krajcik** [comment]
Looks like I'm going to need to incorporate PR #69 Upd Packageinfo into this.

**Comment by Robert-Krajcik** [comment]
OK maybe this is not as easy as I thought
Trying to install an earlier version of `tidyr` or `dplyr` in `tempdir()` is a bit of a challenge.
I try to detach the package first, but
```{r, eval=FALSE}
Warning message:
‘tidyr’ namespace cannot be unloaded:
  namespace ‘tidyr’ is imported by ‘tidyverse’, ‘broom’, ‘highcharter’ so cannot be unloaded 
```

**Comment by Robert-Krajcik** [comment]
@marlycormar, @AARON-CLARK, @MayaGans 
The assumption here is that we should be able to obtain package info and metrics on **any** version of **any** package
There are two ways to obtain package info:

1.  Web-scrape (only works for the **latest** version)
2.  Read the DESCRIPTION file.  
    For a version that is not yet installed, we can install into a temporary directory `tempdir()`

The `packinfo()` function I wrote below (in utils.R) relies on the `riskmetric pkg_ref()` function.
I am currently using the `remotes` package to do the install;  The `versions` package relies on MRAN and it seems flaky at times.

To avoid warning messages like
`Warning: package ‘rvest’ is in use and will not be installed`
I detach the package first and then re-attach the installed version (if it exists)

But some packages can be hard to work with:
```{r, eval=FALSE}
Warning message:
‘dplyr’ namespace cannot be unloaded:
  namespace ‘dplyr’ is imported by ‘broom’, ‘tidyr’, ‘highcharter’ so cannot be unloaded
```

Any thoughts on this?  Is there another way to do this?

```{r, eval=FALSE}
packinfo <- function(package, versn) {
  
  # vrsn_lst <- versions::available.versions(package)
  # vrsn_vec <- unlist(vrsn_lst[[1]]$version)
  vrsn_vec <- get_versns(package) # more efficient (in utils.R)
  
  if (package %in% installed.packages()[,1] && versn == gsub("'",'"',packageVersion(package)) ) {
    package_rm <- pkg_ref(package)
  } else {
    detach_package(package)
    # versions::install.versions(package, versn, lib=tempdir(), quiet = TRUE, type = "source")
    remotes::install_version(package, version = versn, lib = tempdir(), repos = "http://cran.us.r-project.org", quiet = TRUE, upgrade = "never")
    package_rm <- pkg_ref(paste0(gsub("\\\\","/",tempdir()),"/",package)) 
    if (package %in% installed.packages()[,1]) {
    library(package,character.only=TRUE, lib.loc = .libPaths(), verbose = FALSE)
    }
  }
  descr <- package_rm$description %>% as_tibble()
  
  # Need to remove single quotes from Title and Description
  descr$Title       <- str_replace_all(descr$Title, "'", "")  
  descr$Description <- str_replace_all(descr$Description, "'", "")
  
  return(list(ver= descr$Version, title= descr$Title, desc= descr$Description, 
              main= descr$Maintainer, auth= descr$Author, lis= descr$License, pub=descr$Packaged))
  
}
```

**Comment by Robert-Krajcik** [comment]
Funny Thing,
with detaching and re-attaching the package,
it complains about dplyr
but still gives information about the version we want anyway

```{R, eval=FALSE}
[1] "package:dplyr being detached"
Warning: ‘dplyr’ namespace cannot be unloaded:
  namespace ‘dplyr’ is imported by ‘broom’, ‘tidyr’, ‘highcharter’ so cannot be unloaded
```

**Comment by Robert-Krajcik** [comment]
Success!
Starting with an empty database, and using the following 10 items in my .csv file

package | version | comments
-- | -- | --
DT | 0.12 | package and version installed
gt | 0.2.2 | package not installed
rvest | 0.3.6 | package and version installed
rvest | 0.3.8 | version does not exist
rvest | 0.3.2 | version 0.3.6 installed
tidyr | 1.1.0 | version 1.1.2 installed
mas_tidy | 1.1.0 | package does not exist
glue | 1.4.2 | package and version installed
glue | 1.3.2 | version 1.4.2 installed
dplyr | 1.0.0 | version 1.0.2 installed

Here are the messages
```{r, eval=FALSE}
Listening on http://127.0.0.1:5043
Read 15 items
Read 14 items
Read 12 items
Read 6 items
Read 9 items
{"timestamp": "2020-10-01T12:59:19-0400", "log_lvl": "INFO", "log_msg": "Version 0.3.8 of  rvest not found on CRAN. Check your spelling."}
Version 0.3.8 of  rvest not found on CRAN. Check your spelling.
{"timestamp": "2020-10-01T12:59:20-0400", "log_lvl": "INFO", "log_msg": "Package mas_tidy not found on CRAN. Names are case-sensitive. Check your spelling."}
Package mas_tidy not found on CRAN. Names are case-sensitive. Check your spelling.
```
And we get info on all 8 packages and versions, two versions of rvest and two versions of glue
image
image

It took me a while to understand the difference between `detach()` and `unload()`
To install a version of a package in a temporary directory, we need to first detach the package.
That is, remove it from the `search()` path.   Unloading it is not necessary, as we are going reattach it 
once the different version of the package has been installed.

And BTW, I removed `tidyverse` from `setup.R` as it adds eight packages plus itself to the search path.

**Comment by Robert-Krajcik** [comment]
Updated `packinfo()` function
```{r, eval=FALSE}
packinfo <- function(package, versn) {

  if (package %in% installed.packages()[,1] && versn == gsub("'",'"',packageVersion(package)) ) {
    package_rm <- pkg_ref(package)
  } else {
    # is it on the search() path? then detach / install / attach
    if (package %in% (.packages())) {  
    detach_package(package)
    versions::install.versions(package, versn, lib=tempdir(), quiet = TRUE, type = "source")
    require(package, character.only=TRUE, lib.loc = .libPaths(), quietly = TRUE, warn.conflicts = FALSE)
   } else {
     # using remotes to do the install
     remotes::install_version(package, version = versn, lib = tempdir(), repos = "http://cran.us.r-project.org", quiet = TRUE, upgrade = FALSE)
   }
    package_rm <- pkg_ref(paste0(gsub("\\\\","/",tempdir()),"/",package)) 
    # remove.packages(package, lib = tempdir())
  }
  descr <- package_rm$description %>% as_tibble()
  
  # Need to remove single quotes from Title and Description
  descr$Title       <- str_replace_all(descr$Title, "'", "")  
  descr$Description <- str_replace_all(descr$Description, "'", "")
  
  return(list(ver= descr$Version, title= descr$Title, desc= descr$Description, 
              main= descr$Maintainer, auth= descr$Author, lis= descr$License, pub=descr$Packaged))
  
}
```

**Comment by Robert-Krajcik** [comment]
I've decided to use `versions::install.versions()` wherever possible.
But in cases where the MRAN snapshot wasn't taken the day that package version was released...
```{r, eval=FALSE}
> package <- "gt";    versn <- "0.2.2"  # package not installed
> versions::install.versions(package, versn, lib=tempdir(), quiet = TRUE, type = "source")
Warning: unable to access index for repository https://cran.microsoft.com/snapshot/2020-08-06/src/contrib:
  cannot open URL 'https://cran.microsoft.com/snapshot/2020-08-06/src/contrib/PACKAGES'
```
we will try to use install_version instead.
So the `packinfo()` function is once again redesigned and a new one called `install_tempdir()` is created.
This time when we try to install gt version 0.2.2
```{r, eval=FALSE}
{"timestamp": "2020-10-02T08:55:46-0400", "log_lvl": "INFO", "log_msg": "MRAN snapshot not available for gt version 0.2.2 using install_version() instead."}
MRAN snapshot not available for gt version 0.2.2 using install_version() instead.
```
Here are the functions I wrote to `utils.R` in case anyone would like to comment on them.

```{r, eval=FALSE}
install_tempdir <- function(package, versn) {
  tryCatch(
    expr = {
      versions::install.versions(package, versions= versn, lib=tempdir(), quiet = TRUE, type = "source")
    },
    warning = function(w) {
      if(grepl("cannot open URL 'https://cran.microsoft.com", w$message)){
        message(paste("MRAN snapshot not available for",package,"version",versn,"using install_version() instead."))
        remotes::install_version(package, version = versn, lib = tempdir(), repos = "http://cran.us.r-project.org", quiet = TRUE, upgrade = FALSE)
      }
    }
  ) # End of tryCatch
}

packinfo <- function(package, versn) {
  if (package %in% installed.packages()[,1] && versn == gsub("'",'"',packageVersion(package)) ) {
    package_rm <- pkg_ref(package)
  } else {
      if (package %in% (.packages())) {  
      # is it on the search() path? then detach / install / attach
      detach_package(package)
      install_tempdir(package, versn)
      require(package, character.only=TRUE, lib.loc = .libPaths(), quietly = TRUE, warn.conflicts = FALSE)
     } else {
       install_tempdir(package, versn)
     }
      package_rm <- pkg_ref(paste0(gsub("\\\\","/",tempdir()),"/",package)) 
  }
  descr <- package_rm$description %>% as_tibble()
  
  # Need to remove single quotes from Title and Description
  descr$Title       <- str_replace_all(descr$Title, "'", "")  
  descr$Description <- str_replace_all(descr$Description, "'", "")
  
  return(list(ver= descr$Version, title= descr$Title, desc= descr$Description, 
              main= descr$Maintainer, auth= descr$Author, lis= descr$License, pub=descr$Packaged))
  
}

# this is to ensure that all copies of a package are detached.
detach_package <- function(pkg)
{
  search_item <- paste("package", pkg, sep = ":")
  while(search_item %in% search())
  {
    detach(search_item, character.only = TRUE, unload = FALSE)
  }
}

get_versns <- function(package) {
  # given package name, return char vector of versions
  # using package versions seems really slow  
  # vrsn_lst <- versions::available.versions(package)
  # vrsn_vec <- unlist(vrsn_lst[[1]]$version)
  # this code replaces it.
  pkg_html <- read_html(paste0("https://github.com/cran/", package, "/tags"))
  pkg_nodes_v <- html_nodes(pkg_html, 'h4')
  pkg_text_v <- html_text(pkg_nodes_v)
  pkg_text_v <- str_split(pkg_text_v,"\n")
  pkg_vers <- rep("", length(pkg_text_v))
  for (k in 1:length(pkg_text_v)) {
    pkg_vers[k]<-(trimws(pkg_text_v[[k]][3]))
  }
  return(pkg_vers[which(!is.na(pkg_vers))]) 
}
```

**Comment by Robert-Krajcik** [comment]
This last commit update the UIs.
Until **both** package and version have been selected,
this is all that will be showing on the reports, maintenance metrics, community usage metrics and testing metrics tabs
image

**Comment by Robert-Krajcik** [comment]
FYI @marlycormar 
After merging #70, there are a couple of things I need to resolve here.

```{r, eval=FALSE}
$ git checkout fix_versioningII
Switched to branch 'fix_versioningII'

rkrajcik@US-R093989  ~/OneDrive - Biogen/Documents/R/RiskAssessment/risk_assessment-master (fix_versioningII)
$ git merge master
CONFLICT (modify/delete): setup.R deleted in master and modified in HEAD. Version HEAD of setup.R left in tree.
Auto-merging app.R
Auto-merging Server/uploadpackage.R
Auto-merging Server/tm_report.R
CONFLICT (content): Merge conflict in Server/tm_report.R
Auto-merging Server/testing_metrics.R
CONFLICT (content): Merge conflict in Server/testing_metrics.R
Auto-merging Modules/dbupload.R
Automatic merge failed; fix conflicts and then commit the result.
```

**Comment by Robert-Krajcik** [comment]
PR #63 Merge conflicts resolved, @marlycormar

**Comment by marlycormar** [comment]
Hi @Robert-Krajcik, the package versioning seems to work great! This a BIG PR so it'll probably have a lot of minor issues.

I added some comments on the code. Here are some further comments:

1. If a package is not found (either the package is misspelled _or_ the version is incorrect), we need to add it as an undiscovered packages (table on the upload packages tab).

2. On the error message displayed on the console when the package is not found, I would remove the part that refers to CRAN as we also look for locally installed packages as well as packages on GitHub. 

3. The app stays idle after jumping to the 'Package Review History'. Steps to reproduce: Upload a package, select package and version, go to 'Package Review History', return to dashboard, click any tab, e.g. 'Report Review' tab.

(I will keep adding comments as I move along the code =)

**Comment by Robert-Krajcik** [comment]
Thanks for looking at this PR, @marlycormar !
I can make changes 1 and 2 above and review number 3 in your list of comments

**Comment by Robert-Krajcik** [comment]
image

**Comment by Robert-Krajcik** [comment]
Hi @marlycormar 
I think I resolved all your comments so far.

**Comment by marlycormar** [comment]
Hi @Robert-Krajcik, thanks for making these changes so quickly!

The table on the upload packages tab now reflects the loaded csv. I noticed that if only one package is uploaded and that package or version number don't exist, the tables shows 2 undiscovered packages instead of just 1:

Screen Shot 2020-10-19 at 4 51 30 PM

**Comment by Robert-Krajcik** [comment]
**FIXED**
image
I needed to move this code
```{r, eval=FALSE}
      if (any(j)) {
        # add any undiscovered packages here
        values$Undis <- bind_rows(values$Undis, values$New[which(j),])
        # drop the undiscovered packages from New
        values$New <- values$New[-which(j),]
        # reset the row numbers
        row.names(values$New) <- NULL
      }
```
inside of
```{r, eval=FALSE}
    if (nrow(values$New) != 0) {
```
as it was double-counting the error.

As an additional test, I commented out setting j[i] to TRUE
```{r, eval=FALSE}
      if (!pkgs_file$version[i] %in% vrsn_vec) {
        message(paste("Version",pkgs_file$version[i],"of ",pkgs_file$package[i],"not found. Check the version carefully."))
        # j[i] <- TRUE
      }
```
to see if 
`rc <- get_packages_info_from_web(new_package,new_version)`
could handle the error, and see if 
`values$Undis <- bind_rows(values$Undis, values$New[which(j),])`
worked correctly and they both did.

```{r, eval=FALSE}
Listening on http://127.0.0.1:6932
{"timestamp": "2020-10-21T09:51:27-0400", "log_lvl": "INFO", "log_msg": "Package BrBa not found. Names are case-sensitive. Check your spelling."}
Package BrBa not found. Names are case-sensitive. Check your spelling.
{"timestamp": "2020-10-21T09:51:30-0400", "log_lvl": "INFO", "log_msg": "Version 0.3.8 of  rvest not found. Check the version carefully."}
Version 0.3.8 of  rvest not found. Check the version carefully.
{"timestamp": "2020-10-21T09:51:53-0400", "log_lvl": "ERROR", "log_msg": "Error in extracting general info of the package rvest info Error in version_to_date(pkgs = pkgs__COMMA__ versions = versions): 0.3.8 does not appear to be a valid version of 'rvest'.__LF__Use available.versions('rvest') to get valid versions__LF__", "app": "using packinfo function"}
```
image

**Comment by marlycormar** [comment]
Thanks @Robert-Krajcik. That error is now fixed.

**Comment by marlycormar** [comment]
Other issues I found:

1. **Reprex:** select a package and version, then upload a package. The 'select package' dropdown resets to 'Select' whereas the 'select version' doesn't. **Potential solution:** set an observer so that when 'select package' equals 'Select' the 'select version' dropdown will also set to 'Select.

2. **Reprex:** right after doing reprex 1, go to 'Maintaince Metrics' tab. The page keeps trying to load uncessfully. **Potential solution:** make each tab display only if both a package and a version are selected (not only a package).

3. **Reprex:** with an empty db, load a csv file with only _dplyr_ and version _1.0.0_. The upload/save to the db takes more than 10s. It is longer when uploading multiple packages. Is this time increase only happening to me?

Will stop for now @Robert-Krajcik as other issues may be fixed by working on the above. Thanks!

**Comment by Robert-Krajcik** [comment]
Thanks @marlycormar for finding these issues.
I will look into them today and come up with fixes.

**Comment by Robert-Krajcik** [comment]
In sidebar.R about line 139
```{r, eval=FALSE}
observeEvent(input$select_pack, {
    # req(input$select_pack != "Select")
    pack_ver<-db_fun(paste0("SELECT version FROM Packageinfo WHERE package = '", input$select_pack, "'"))
      updateSelectizeInput(
        session,
        "select_ver",
        choices = c("Select", pack_ver[,1]),
        selected = "Select"
      )
```
the "req()" statement was not necessary and was commented out.
This fixed issue Reprex 1

I also checked to make sure this didn't break the previous fix
`PR and Package Review History play nice with each other`

And as a result,
This also seems to have fixed issue Reprex 2 -- or perhaps I could not reproduce it.
image

**Comment by Robert-Krajcik** [comment]
For issue/reprex 3,
I did some basic timings in uploadpackage.R after deleting the database and loading only the dplyr package.
```{r, eval=FALSE}
      for (i in 1:nrow(values$New)) {
          new_package<-values$New$package[i]
          new_version<-values$New$version[i]
          t0 <- Sys.time()
          rc <- get_packages_info_from_web(new_package,new_version)
          dif1 <- Sys.time() - t0
          print(dif1)
          if (rc != "" && rc == "ERROR") {
            j[i] <- TRUE
            next
          }
          t0 <- Sys.time()
          metric_mm_tm_Info_upload_to_DB(new_package,new_version)
          dif1 <- Sys.time() - t0
          print(dif1)
          t0 <- Sys.time()
          metric_cum_Info_upload_to_DB(new_package,new_version)
          dif1 <- Sys.time() - t0
          print(dif1)
```
Results:
```{r, eval=FALSE}
Time difference of 0.09124923 secs
Time difference of 4.283855 secs
Time difference of 6.133133 secs
```
This is what the R Profiler looks like for `metric_mm_tm_Info_upload_to_DB(new_package,new_version)`
```{r, eval=FALSE}
          Rprof() # start the profiler
          metric_mm_tm_Info_upload_to_DB(new_package,new_version)
          Rprof(NULL)
```
```{r, eval=FALSE}
> summaryRprof()
$by.self
                             self.time self.pct total.time total.pct
"open"                            1.94    55.43       1.94     55.43
"request_fetch.write_memory"      0.94    26.86       0.96     27.43
"parse_con"                       0.18     5.14       2.12     60.57
"grepl"                           0.06     1.71       0.08      2.29
"readRDS"                         0.06     1.71       0.06      1.71
"vapply"                          0.04     1.14       0.04      1.14
"lapply"                          0.02     0.57       3.50    100.00
```
**This should be in a separate issue, and have a separate PR address it.**

**Comment by Robert-Krajcik** [comment]
Results of some tests involving installation of a package and version
Test using versions::install.versions versus remotes::install_version versus remotes::install_url

Test | T1 | T2 | T3 | T4
-- | -- | -- | -- | --
  | 11.56035 | 13.47421 | 12.49219 | 11.82073
  | 9.457219 | 9.998638 | 10.78017 | 10.69238
  | 9.552815 | 9.728435 | 10.75229 | 10.94789
  | 10.29969 | 9.626506 | 11.27578 | 10.06431
  | 11.06525 | 10.61041 | 11.30438 | 9.688558
  | 11.1907 | 9.754209 | 10.86205 | 9.492014
  | 10.13055 | 11.06655 | 10.62579 | 9.741511
  | 10.45576 | 9.665578 | 11.05506 | 9.335925
  | 12.81505 | 10.26415 | 10.93417 | 11.57382
  | 12.3462 | 10.40088 | 11.65848 | 9.880879
  |   |   |   |  
Mean | 10.8873584 | 10.4589566 | 11.174036 | 10.3238017
SD | 1.123065647 | 1.159014488 | 0.557988192 | 0.88207841
  |   |   |   |  
package_name   <- "forcats"; package_version <- "0.1.0" |  
T1 = install   packge using versions::install.versions |  
T2 = install   packge using remotes::install_version |  
T3 = install   packge using remotes::install_url |  
T4 = install   packge using remotes::install_version + Ncpus = parallel::detectCores()

**Comment by Robert-Krajcik** [comment]
Commit 931b61c is a small performance improvement, can save 15-20 seconds when loading five packages.
Commit d646713 replaces packageVersion (which actually returns int) with getNamespaceVersion (which returns chr)
example:
```{r)
packs <- list("purrr","forcats","rvest","glue","dplyr","ggplot2","readr","haven")
inst_ver <- map_chr(packs, ~ getNamespaceVersion(.x))
```

**Comment by Robert-Krajcik** [comment]
Now I can see why `get_packages_info_from_web()` in `dbupload.R` used web-scraping, and only resorted to using `read.dcf()` to read the description file for the currently installed package when it caught an error.  -- it is pretty fast.

However, the `pkg_ref_cache.description.R` function in riskmetric only has two classes defined: `pkg_install` and `pkg_source`.
Both methods use `read.dcf()`.  The first one uses the `.libPaths()` directory implicitly; the second uses an explicit directory, like  `tempdir()`  to refer to the location of the package and version installed.

We could probably write a method for `pkg_remote`, similar to this:
```{r, eval=FALSE}
pkg_ref_cache.description.pkg_remote <- function(x, name, ...) {
  webpage <-
    read_html(paste0(
      "https://cran.r-project.org/web/packages/",
      package
    ))
  
  title_html <- html_nodes(webpage, 'h2')
  title <- html_text(title_html)
  title <- str_replace_all(title, "\n  ", "")
  title <- str_replace_all(title, "'", "")
  title <- str_replace_all(title, '"', "")
  
  desc_html <- html_nodes(webpage, 'p')
  desc <- html_text(desc_html)
  desc <- desc[1]
  desc <- str_replace_all(desc, "\n  ", "")
  desc <- str_replace_all(desc, "'", "")
  desc <- str_replace_all(desc, '"', "")
  
  this_node <- function(text) {
    zz_html <- html_nodes(webpage, 'td')
    zz_text<-html_text(zz_html)
    for(i in 1:length(zz_text)){
      if(!is.na(zz_text[i])){
        if(zz_text[i] == text){
          zz_text<-zz_text[i+1]
        }
      }
    }
    zz_text <- str_replace_all(zz_text, "\n  ", "")
    zz_text <- str_replace_all(zz_text, "'", "")
    zz_text <- str_replace_all(zz_text, '"', "")
  }
  
  vrsn <- this_node("Version:")
  dpnd <- this_node("Depends:")
  main <- this_node("Maintainer:")
  auth <- this_node("Author:")
  publ <- this_node("Published:")
  lisc <- this_node("License:")
  impr <- this_node("Imports:")
  
  return(list(Package = package, Title = title, Version = vrsn, Author = auth, Depends = dpnd,
              Description = desc, License = lisc, Imports = impr, Maintainer = main, Packaged = publ)) 
}
```

**Comment by Robert-Krajcik** [comment]
I was testing a package called `survey` version `4.0` but `read.csv()` kept insisting on reading the version as a dbl instead of a chr.

**Comment by Robert-Krajcik** [comment]
I was trying to install `survminer` and discovered that `install.versions()` was trying to install all the dependencies first.
But we don't need them, just need to be able to read the description file out of the tempdir()

**Comment by Robert-Krajcik** [comment]
Another performance improvement:
in `dbupload.R` why are we going through `pkg_ref()` and `pkg_assess()` twice?
```{r, eval=FALSE}
  package_riskmetric1 <<-
    pkg_ref(package_name) %>%
    as_tibble() %>%
    pkg_assess() %>%
    pkg_score() %>%
    mutate(risk = summarize_scores(.))
  
  package_riskmetric2 <<-
    pkg_ref(package_name) %>%
    as_tibble() %>%
    pkg_assess()
```
A simple redesign saves 2-5 seconds per package/version:
```{r, eval=FALSE}
  package_riskmetric2 <<-
    pkg_ref(package_name) %>%
    as_tibble() %>%
    pkg_assess()
  
  package_riskmetric1 <<-
    package_riskmetric2 %>% 
    pkg_score() %>%
    mutate(risk = summarize_scores(.))
```

```{r, eval=FALSE}
> package_name <- "glue"; package_version <- "1.4.2"  # pkg_install
> t1 <- Sys.time()
>   package_riskmetric1 <<-
+     pkg_ref(package_name) %>%
+     as_tibble() %>%
+     pkg_assess() %>%
+     pkg_score() %>%
+     mutate(risk = summarize_scores(.))
>   
>   package_riskmetric2 <<-
+     pkg_ref(package_name) %>%
+     as_tibble() %>%
+     pkg_assess()
>   
>   print(Sys.time() - t1)
Time difference of 6.478495 secs
> package_name <- "forcats"; package_version <- "0.5.0"  # pkg_install
> t1 <- Sys.time()
>   package_riskmetric2 <<-
+     pkg_ref(package_name) %>%
+     as_tibble() %>%
+     pkg_assess()
>   
>   package_riskmetric1 <<-
+     package_riskmetric2 %>% 
+     pkg_score() %>%
+     mutate(risk = summarize_scores(.))
>   
>   print(Sys.time() - t1)
Time difference of 2.497833 secs
```

**Comment by Robert-Krajcik** [comment]
This is just too old to pursue anymore.

**Pull request closed without merging**
