### PR TITLE
Make Pkg Risk Score more visible

### LINKED ISSUE #71: Improve the way the risk is displayed
Make the risk score more obvious

### PR DESCRIPTION
**Pull request by AARON-CLARK**
Closes #71.

I made my own version of a `shinydashboard::valueBox()` as I found it quite inflexible. I also made sure the color of the `wellPanel()` mimics that which is found on the `db_dash_screen`. Thoughts?

image

image

image

### CODE REVIEW

**Review by Robert-Krajcik — COMMENTED** [review]
This is pretty spiffy, @AARON-CLARK 
Just wondering if the Status should be different for "under review" versus reviewed?
Maybe a darker grey with white letters for "under review" and lighter grey with black letters for "reviewed"?

**Comment by Robert-Krajcik** [comment]
OK @AARON-CLARK let me see if I can figure something out.

**Comment by Robert-Krajcik** [comment]
This took me a while to figure ths out, @AARON-CLARK 
I went down a rabbit hole looking at reactive variables, 
but in the end decided to follow what you had already done for 
the wellPanel BoxScore
The text font is white for NA, black for Not Reviewed, and blue for Reviewed

```{r, eval=FALSE}
# change the color of the status wellPanel
observe({
  req(input$select_pack)
  valBoxColor <- case_when(
    input$select_pack == "Select" ~ "white",
    !is_empty(values$selected_pkg$decision) && values$selected_pkg$decision == "" ~ "black",
    TRUE ~ "blue"
  )
  runjs(sprintf("
                document.getElementById('%s').style.color = '%s';
                ", "diyValBoxStatus", valBoxColor))
})
```

**Comment by AARON-CLARK** [comment]
Thanks @Robert-Krajcik, I like that change. Merging!

**Pull request merged**
