### PR TITLE
Metric Weight Configuration

### PR DESCRIPTION
**Pull request by Jeff-Thompson12**
Addresses #482

### CODE REVIEW

**Comment by Jeff-Thompson12** [comment]
I'm not entirely sure why the tests were failing. It does not seem like it should have been related to this PR, but here we are.

**Review by AARON-CLARK — COMMENTED** [review]
I can't find anything wrong with this PR, which means I must be slipping. I'll wait for @borgmaan & @Xyarz to give it a look.

I think once this PR is merged, we'll have to include a new card for the covr_coverage metric. We've kind of been ignoring it for a long time, but just adding a "Percentage card" similar to bug closure rate (seen below) with updated labels should do the trick. I'll create a new issue.

image

**Review by Xyarz — APPROVED** [review]
Looks also good to me. Can't find anything either. Tested and everything worked as intended,

**Review by AARON-CLARK — CHANGES_REQUESTED** [review]
@Jeff-Thompson12, you composed a perfect PR. @Xyarz & I couldn't find anything wrong with it. Congratulations!

Could you bump the version number & updates the `NEWS` and we'll get this one merged!

**Comment by Jeff-Thompson12** [comment]
I'm just sad that neither one of you mentioned the inclusion of the new reactive `trigger_events` being passed between modules now that will enable communication between different parts of the application without making modules directly connected to each other.

**Comment by Jeff-Thompson12** [comment]
Nevermind, that was one of my imperfect PRs. They blend together for me.

**Pull request merged**
