### PR TITLE
Redo docx report Rmd

### PR DESCRIPTION
**Pull request by marlycormar**
_Note:_ The docx report doesn't look that good, but it works. We may need to revisit it at some point.

### CODE REVIEW

**Review by Robert-Krajcik — CHANGES_REQUESTED** [review]
Unlike the last .docx I pulled, this one is quite readable.
This is package Tplyr
Can we do more with the plot?  Maybe connect the dots at least?
And shouldn't this be by month and not year?
And the package name does not appear on this page.

image

**Comment by marlycormar** [comment]
Yes, the word document report is far from ideal! I don't have much experience creating word document from RMarkdown. Would you like to take over the PR (or merge it and improve it)? @Robert-Krajcik  I think you worked on the previous one and it looked good.

**Comment by Robert-Krajcik** [comment]
OK I'll work on it later today

**Comment by Robert-Krajcik** [comment]
This PR is being replaced with PR #210

**Comment by marlycormar** [comment]
Closing this in favor of https://github.com/pharmaR/risk_assessment/pull/210

**Pull request closed without merging**
