### PR TITLE
Startup Utility Functions Tests

### PR DESCRIPTION
**Pull request by Jeff-Thompson12**
Addresses the startup utility functions of #295.

Includes edits of the said functions.

### CODE REVIEW

**Comment by Jeff-Thompson12** [comment]
The test for `add_tags()` is pretty basic. It's functionality can't really be tested outside of running the application. Open to suggestions though.

**Review by Robert-Krajcik — APPROVED** [review]
I ran both `devtools::test()` and  `devtools;;check()` -- both ran clean.
LGTM.

**Comment by Jeff-Thompson12** [comment]
@Robert-Krajcik the Github Actions are off for the PR right now (even though they are passing). I still need to figure out what is going on with that.

**Comment by AARON-CLARK** [comment]
@Jeff-Thompson12, I just looked and can verify these checks have completed. But I see you just kicked them off again.

image

**Comment by Jeff-Thompson12** [comment]
@AARON-CLARK You can see the issue [here](https://github.com/pharmaR/risk_assessment/actions/runs/3640280325). It appears to be a Github issue and not a code issue though.

**Comment by Jeff-Thompson12** [comment]
@Robert-Krajcik the R CMD check seems to be resolved.

**Comment by Jeff-Thompson12** [comment]
@Robert-Krajcik Is there any reason this PR is not getting approved and merged?

**Comment by Robert-Krajcik** [comment]
I thought we needed another reviewer, but I guess not.  I'll merge it now.

**Pull request merged**
