### PR TITLE
Multi Report Download

### LINKED ISSUE #2: Default report name
The reports all default to the same name, 'Report.html'.  Ideally the default name should contain the package name.  For example, '[pkg_name]_[pkg_version]_risk_assessment'.

### LINKED ISSUE #8: Implement package version functionality
The app only computes metrics on the latest version of the given package, ignoring the version selected in the dropdown.

### PR DESCRIPTION
**Pull request by AARON-CLARK**
**Changelog:**
* Added SQL code to select the package version in two spots to help fix #8 a little
    - reportpreview.R where general info is displayed
    - app.R where values$selected_pkg is created (and used throughout the app)

* Adjusted report download name by pasting the currently selected package name and version number, so now the users report download will say '[pkg_name]_[pkg_version]_risk_assessment.hmtl' instead of report.html. Should fix #2.

* Created a new UI button on "Upload Package" tab that zips a report for each package into the desired file format
    - this required cleaning up the report rmd files and making them truly parameterized. But hey, each report generated uses the same rmd file between the "Report Preview" tab and the "Upload Package", so that's a win.
    - Also involved adding version as an official parameter to add to sql queries

* optimized the progress bar

* I need help with placement of these UI elements (below). I just through them here as a placeholder for now
image

Please pull this branch and test. I'm quite happy with how it works.

### CODE REVIEW

**Comment by AARON-CLARK** [comment]
fixes #1 
fixes #2

**Comment by AARON-CLARK** [comment]
If interested, I created a new branch called [multi_reports_pwalk](https://github.com/pharmaR/risk_assessment/tree/multi_reports_pwalk) that uses purrr's pwalk function instead of a loop to render reports. In summary, I don't like the pwalk solution because when used, the rmarkdown reports aren't inheriting the parent environment from shiny, but rather seem to be operating in a new/ clean environment. This means the rmd file won't automatically find any shiny inputs you pass it without explicitly including them as a parameter to the report. Since there are no gains in speed or code clarity, I don't think it's worth the change.

**Comment by marlycormar** [comment]
> If interested, I created a new branch called [multi_reports_pwalk](https://github.com/pharmaR/risk_assessment/tree/multi_reports_pwalk) that uses purrr's pwalk function instead of a loop to render reports. In summary, I don't like the pwalk solution because when used, the rmarkdown reports aren't inheriting the parent environment from shiny, but rather seem to be operating in a new/ clean environment. This means the rmd file won't automatically find any shiny inputs you pass it without explicitly including them as a parameter to the report. Since there are no gains in speed or code clarity, I don't think it's worth the change.

Thats interesting. Using either the `envir` or the `params` argument should solve this issue.

```
walk(~rmarkdown::render(
  tempReport, output_file = file,
  params = params,
  envir = new.env(parent = globalenv())))
```
But as you said if there is no other advantage in using `purrr`, we don't have to go down that road =)

**Comment by marlycormar** [comment]
@AARON-CLARK can you split this PR so that we only have the multiple reports part of it? The other PR should take longer to review and this one seems more straightforward. The `git cherry-pick` command should come handy here!

**Comment by AARON-CLARK** [comment]
> 
> Thats interesting. Using either the `envir` or the `params` argument should solve this issue.
> 

Right! `rmarkdown::render`'s default argument is `envir = parent.frame()` but for some reason, it was creating a new environment as your code suggests. It's a mystery.

>
> But as you said if there is no other advantage in using purrr, we don't have to go down that road =)
>

I'm easily influenced if you feel we should use the purrr solution. It is obviously sexier code since it leverages the tidyverse and hey, it's already written. Feel free to test.

**Comment by AARON-CLARK** [comment]
> @AARON-CLARK can you split this PR so that we only have the multiple reports part of it? The other PR should take longer to review and this one seems more straightforward. The `git cherry-pick` command should come handy here!

Hi @marlycormar, are you referring to separating out the the areas where I added `version = input$select_ver` to the sql code? Related to #8 ? Or something else?

**Comment by AARON-CLARK** [comment]
Should this multi-report download feature be designed to generate a report for every package in the...
(1) uploaded csv file? The PR is currently built for this.
(2) db file? This would include all packages in the csv + any packages previously reviewed.

**Comment by AARON-CLARK** [comment]
Hey team. I've made the changes we talked about on Monday as a group so this PR is ready for a second pass review. You'll notice these changes:
* got rid of db file
* got rid of loggit.json according to #18
* got rid of any work done for #8 

However, I still need help with consideration:

> Should this multi-report download feature be designed to generate a report for every package in the...
> (1) uploaded csv file? The PR is currently built for this.
> (2) db file? This would include all packages in the csv + any packages previously reviewed.

**Comment by marlycormar** [comment]
Hi @AARON-CLARK, I think for now what you have is a great (keeping it simple :)

**Comment by AARON-CLARK** [comment]
Merged some recent changes from master into this branch. Any reason this can't be merged @marlycormar?

**Comment by marlycormar** [comment]
Hi @AARON-CLARK, I added a comment here https://github.com/pharmaR/risk_assessment/issues/1. If you think we should merge this PR, and then make further changes let me know =)

**Comment by AARON-CLARK** [comment]
> Hi @AARON-CLARK, I added a comment here #1. If you think we should merge this PR, and then make further changes let me know =)

Hi @marlycormar, That plan sounds great. Please merge and then let's work towards creating the "overview" tab/ dashboard.

**Pull request merged**
