### PR TITLE
Prepare database for the addition of metric weights: updating the package table

### PR DESCRIPTION
**Pull request by marlycormar**
### Major changes
- Update `package` table
  - Rename `Packageinfo` to `package`
  - Rename column `package` to `name`
  - Add new column called `weighted_score`
- Update the code that references this table and table column

_Note:_ the vignettes need attention. I'll wait until all the tables are updated to update the vignettes accordingly.

### CODE REVIEW

**Comment by Robert-Krajcik** [comment]
Looking at this now, @marlycormar

**Review by Robert-Krajcik — APPROVED** [review]
No issues running the code, Looks OK to me.

**Comment by marlycormar** [comment]
The AUTOINCREMENT is not working. The id is assigned a NULL by default. Working on a fix...

**Comment by marlycormar** [comment]
I found the issue: "AUTOINCREMENT is only allowed on an INTEGER PRIMARY KEY". After updating the query that creates `package`, the id auto assignment is working.

**Comment by marlycormar** [comment]
@Robert-Krajcik, the id issue should be fixed now.

**Comment by Robert-Krajcik** [comment]
It's working now

image

**Pull request merged**
