### PR TITLE
sidebar minor update

### PR DESCRIPTION
**Pull request by Robert-Krajcik**
remove validate() from update package version step.

One thing I noticed was that 
when you select a package and then go and select "-"
the version does not get reset to "-"

This is because of this piece of code in the "update package version" step
```{r, eval=FALSE}
      if(input$select_pkg == "-")
        validate("Please select a package")
```

### CODE REVIEW

**Comment by marlycormar** [comment]
Fixes the issue!

**Comment by marlycormar** [comment]
Looking further into it, I notice that now it doesn't display the warning message on the metrics' tab when no package is selected.

**Comment by Robert-Krajcik** [comment]
OK I can update this, @marlycormar

**Comment by Robert-Krajcik** [comment]
Hi @marlycormar 
This has been updated now, and works like it did using fix_communityUsagePlot

**Comment by marlycormar** [comment]
LGTM!

**Pull request merged**
