### PR TITLE
Fix versioning

### PR DESCRIPTION
**Pull request by Robert-Krajcik**
ref: #52 -- This is a work in progress

### CODE REVIEW

**Comment by marlycormar** [comment]
Hi @Robert-Krajcik, you have made good progress here. Let me know if you'd like me to review some part or take over a portion of it.

**Comment by Robert-Krajcik** [comment]
Hi @marlycormar 
I can see that the community metrics goes across versions of a package,
so we could have it report/graph **up to** the version selected.
(the note about 11 months of history is hardcoded and will need updating)

But the thing I am grappling with right now is,
how do we influence the version in pkg_assess()?
Assume:
`package_name <- "glue"`
and it is version 1.3.2
Just modifying the version here seems to make no difference

```{r, eval=FALSE}
package_riskmetric1a <<-
  pkg_ref(package_name) %>%
  mutate(version = "1.4.2") %>%
  as_tibble() %>%
  pkg_assess() %>%
  pkg_score() %>%
  mutate(risk = summarize_scores(.))
```

**Comment by Robert-Krajcik** [comment]
Or maybe we just have the database tables and logic set up for multiple versions, and worry about riskmetric assessment later?

**Comment by Robert-Krajcik** [comment]
Replaced by #63

**Pull request closed without merging**
