### PR TITLE
Repair renv.lock

### PR DESCRIPTION
**Pull request by Jeff-Thompson12**
Addresses #690

### CODE REVIEW

**Comment by mayank-procogia** [comment]
Hi @Jeff-Thompson12,

I hypothesized that updating my `renv.lock` exclusively through PPM might resolve this issue, taking inspiration from your recent commits with this issue. 

After observing changes to your `renv.lock` file in [jt-690-repair_renvlock](https://github.com/pharmaR/riskassessment/tree/jt-690-repair_renvlock), I adapted my `renv.lock` to utilize PPM as the sole repository for R package downloads and installations. 

I conducted three tests, involving cloning, executing `renv::restore()`, and launching the application, and all tests were successful.

Please review the [comparing changes between pharmaR/riskassessment:master and mayank-procogia/riskassessment:ppm_renv_fix](https://github.com/pharmaR/riskassessment/compare/master...mayank-procogia:riskassessment:ppm_renv_fix).

Branch: [mayank-procogia/riskassessment:ppm_renv_fix](https://github.com/mayank-procogia/riskassessment/tree/ppm_renv_fix)

**Comment by mayank-procogia** [comment]
As a part of above hypotheses, I went ahead and forked [jt-690-repair_renvlock](https://github.com/pharmaR/riskassessment/tree/jt-690-repair_renvlock) to [mayank-procogia/riskassessment:jt_690_ppm_renv_fix](https://github.com/mayank-procogia/riskassessment/tree/jt_690_ppm_renv_fix) to have all the latest changes from this working branch. 

I then updated `renv.lock` from commit [a4d9570](https://github.com/mayank-procogia/riskassessment/commit/a4d95706f5ce7bed547287fafeefd8367080032f) of [mayank-procogia/riskassessment/dev_renv_fix](https://github.com/mayank-procogia/riskassessment/tree/dev_renv_fix). This fix uses PPM as single repo only, and uses the updated pkgs of `pkgload(1.3.3)`, `rlang(1.1.1)` and `svglite(1.2.3)` which in turn auto updates other packages as renv fix. Note that this is a downgrade of other updated packages from your recent commit.

In essence, this is similar to the previous step but with the other additional commits in this branch for merging, if accepted.

I have tested it out twice in my local involving cloning, executing `renv::restore()`, and launching the application, and all tests were successful.

Please review [comparing changes between pharmaR/riskassessment:jt-690-repair_renvlock and mayank-procogia/riskassessment:jt_690_ppm_renv_fix](https://github.com/pharmaR/riskassessment/compare/jt-690-repair_renvlock...mayank-procogia:riskassessment:jt_690_ppm_renv_fix)

**Comment by mayank-procogia** [comment]
**Second fix**: Downgrading required packages in `renv.lock` with respect to your latest commits in [jt-690-repair_renvlock](https://github.com/pharmaR/riskassessment/tree/jt-690-repair_renvlock) branch.

Downgraded Packages `Matrix(1.4-1)`, `nlme(3.1-157)`, and `svglite(1.2.3)`

As a result, the dependency tree was repaired during package installation:
```
- crul              [1.4.0]
- fontBitstreamVera [0.1.1]
- fontLiberation    [0.1.0]
- fontquiver        [0.2.1]
- gdtools           [0.3.3]
- gfonts            [0.2.0]
- httpcode          [0.3.0]
```

Please review [comparing changes between pharmaR/riskassessment:jt-690-repair_renvlock and mayank-procogia/riskassessment:/jt_690_renv_Matrix](https://github.com/pharmaR/riskassessment/compare/jt-690-repair_renvlock...mayank-procogia:riskassessment:jt_690_renv_Matrix)

Branch: [mayank-procogia/riskassessment:jt_690_renv_Matrix](https://github.com/mayank-procogia/riskassessment/tree/jt_690_renv_Matrix) forked from [pharmaR/riskassessment:jt-690-repair_renvlock](https://github.com/pharmaR/riskassessment/tree/jt-690-repair_renvlock)

Deployed Content on ProCogia RS Connect for testing: 

- `mayank-procogia:riskassessment:jt_690_renv_Matrix`: https://procogia.acuna.cloud/risk-demo-Matrix-29112023/
- `pharmaR/riskassessment:jt-690-repair_renvlock`: https://procogia.acuna.cloud/risk-demo-29112023/

Note: 
- When deploying to ProCogia RS Connect with the latest changes in `pharmaR/riskassessment:jt-690-repair_renvlock` it deploys successfully, however it fails on my local (Mac) system. [Link](https://procogia.acuna.cloud/risk-demo-Matrix-29112023/)
- Using `mayank-procogia:riskassessment:jt_690_renv_Matrix` for deployment is successful on both local and RSC. [Link](https://procogia.acuna.cloud/risk-demo-29112023/)

**Comment by Jeff-Thompson12** [comment]
@mayank-procogia it might be helpful to explain a little background into why the `renv.lock` file has been changed. In the project we always had a mix of packages and download dates (i.e. even though we originally had a snapshot set, not all packages were from that time point). When MRAN got decommissioned, we had to update `renv`. This caused issues with downloading packages that required versions post the snapshot date (e.g. you had to run `utils::install.packages("shinyTree") to install the package). We then chose to remove the snapshot date. The deployment sans snapshot date was working on our windows systems and the Linux systems on both GHAs and our deployments.

I say all this to express that in my opinion while aligning all the package versions to a snapshot date in PPM is desirable, I'm not really of the opinion that we should be hunting for package versions outside of the snapshot for system specific installations. Our design philosophy has been to develop with server deployment in mind.

Did you try to resolve Fortran issue you ran into on your Macbook? I'm not sure how feasible that would be.

@AARON-CLARK do you have any comment/opinion you would like to share?

**Comment by mayank-procogia** [comment]
Hi @Jeff-Thompson12, 
 
I attempted to resolve the Fortran issue on my MacBook but hit a dead end. 

I've encountered similar problems with the latest versions of `svglite` in other Shiny projects and found that downgrading to a stable version `(1.2.3)` often resolved the issue. Similarly, downgrading `Matrix(1.4-1)` and `nlme(3.1-157)` addressed **C++** and **Fortran** issues on Mac, avoiding the need for hot fixes. I have experienced similar fixes for other applications pacakges snapshot while working on Windows too. My goal was to streamline the process with `renv` ensuring seamless handling during the initial clone and renv restore on all of the systems.

The initiative to identify and modify packages in the `renv.lock` file was undertaken to ensure compatibility across Windows, Linux, and Mac systems.

For now, we can overlook this additional fixes, as the deployment on Linux, Windows, GHAs and RS Connect works as expected with your fix and PPM date snapshot. This suffices for us to deploy it on a Linux based infrastructure with persistent storage, in line with `riskassessment` future plans.

I have a meeting with Aaron tomorrow and will keep you updated after our discussion. 

Thanks

**Review by AARON-CLARK — APPROVED** [review]
Per discussion, this PR looks good. Also, I pulled down and tested with no noticeable issues. Thanks @Jeff-Thompson12.

**Pull request merged**
