### PR TITLE
Db fun update

### PR DESCRIPTION
**Pull request by Robert-Krajcik**
Updated utils.R and dbupload.R
Need to use dbClearResult or dbGetQuery
And need to use dbExecute() to perform delete, update or insert queries
added a new function db_ins()
updated uploadpackage.R (use observeEvent instead of observe)
Added loggit.json to .gitignore

Still seeing warning messages about:

`Warning in error_handler(x, ...) :<br>
  no available scoring algorithm for metric of class "pkg_metric_error", returning default score of 0.`

But these seem to be coming from a function buried in the package.

### CODE REVIEW

**Comment by Robert-Krajcik** [comment]
The warning message above is coming from function `pkg_score()` from the `riskmetric` package
```{r}
library(riskmetric)
pkg_ref("ggplot2") %>%
  as_tibble() %>%
  pkg_assess() %>%
  pkg_score() %>%
  mutate(risk = summarize_scores(.))
```

`Warning message:
In error_handler(x, ...) :
  no available scoring algorithm for metric of class "pkg_metric_error", returning default score of 0.`

**Comment by AARON-CLARK** [comment]
Hi @Robert-Krajcik, I merged some recent db changes @marlycormar wrote, so it looks like there is a merge conflict on this branch now. Apologies!

**Comment by Robert-Krajcik** [comment]
OK ready for your review  @AARON-CLARK

**Comment by AARON-CLARK** [comment]
Hi @Robert-Krajcik, The console is a lot cleaner! I am not getting nearly as many warnings as I was previously. Specfically, the `Warning in connection_release@conn@ptr`  is gone, as is `Warning in result_fetch(res@ptr, n = n)`.

However, should that score warning / error have gone away? I'm still getting it:

image

**Comment by Robert-Krajcik** [comment]
That warning message, as I mentioned earlier
is coming from function pkg_score() from the riskmetric package

**Pull request merged**
