### PR TITLE
Replace queries to the MaintenanceMetric table with queries to package, metric, package_metrics

### PR DESCRIPTION
**Pull request by marlycormar**

### CODE REVIEW

**Comment by Robert-Krajcik** [comment]
Hi @marlycormar 
How about if we do #104 and #105 first, and then look at what else we need to change?
The metric table is going to be initialized dynamically; no need to fix it.

**Review by Robert-Krajcik — APPROVED** [review]
Well, it works. @marlycormar 

But this is still some hardcoding here.
I was looking at refactoring all this so we don't have to touch the code when we get new metrics.
But right now my efforts feels like I'm trying to fix the landing gear while we're flying the plane.

**Comment by Robert-Krajcik** [comment]
As I think about it,
The WEIGHT on the metric and package_metrics tables should be REAL instead of INT

**Comment by marlycormar** [comment]
> Well, it works. @marlycormar
> 
> But this is still some hardcoding here.
> I was looking at refactoring all this so we don't have to touch the code when we get new metrics.
> But right now my efforts feels like I'm trying to fix the landing gear while we're flying the plane.

Hey @Robert-Krajcik, thanks for reviewing the PR!

It makes sense that there is still hardcoding in the PR as this PR is not meant to fix that issue in the app. This PR prepares the db for the addition of weights, and although I did have to refactor some of it on the way, it was not the intended focus.

**Comment by marlycormar** [comment]
> As I think about it,
> The WEIGHT on the metric and package_metrics tables should be REAL instead of INT

Not sure why the type INT worked, but I changed it to DECIMAL as I found it recommended over REAL. What do you think?

**Comment by Robert-Krajcik** [comment]
I know REAL is equivalent to R dbl (double-precision floating point)
SQLite recommended DECIMAL over REAL?  
How many decimal points can it handle?
If you think it will work, then go with it.

**Comment by marlycormar** [comment]
To be honest, I searched for SQL and not SQLITE. Searching now for SQLITE, it seems that it 'understands' DECIMAL types but it is not native to SQLITE. Although it works as it is, I don't like that it is not native to SQLITE. So I will update the types.

**Comment by marlycormar** [comment]
What is puzzling is that it was working before with INT ¯\_(ツ)_/¯

**Comment by marlycormar** [comment]
Done @Robert-Krajcik!

**Pull request merged**
