### PR TITLE
Fix error when deselecting package

### PR DESCRIPTION
**Pull request by Jeff-Thompson12**
Tracked down the source of the error. Simple fix.

### CODE REVIEW

**Comment by Robert-Krajcik** [comment]
Nice and simple solution @Jeff-Thompson12 
FYI, any of these would work:
```{r, eval=FALSE}
if (length(pkg_name) == 0) return("")
if (identical(pkg_name, character(0))) return("")
if (is_empty(pkg_name)) return("")
req(pkg_name)
```

**Comment by Robert-Krajcik** [comment]
Resolving global.R
```{r, eval=FALSE}
<<<<<<< fix-error-when-deselecting-pkg
showComments <- function(pkg_name, comment_type){
  if (length(pkg_name) == 0)
    return("")
  
  comments <- dbSelect(
    glue(
      "SELECT user_name, user_role, comment, added_on
      FROM comments
      WHERE id = '{pkg_name}' AND comment_type = '{comment_type}'"
    )
  ) %>%
    map(rev)
  
=======
showComments <- function(pkg_name, comments){
>>>>>>> dev
  ifelse(
    length(comments$user_name) == 0, 
    "No comments",
    paste0(
      "<div class='well'>",
      icon("user-tie"), " ", "user: ", comments$user_name, ", ", 
      icon("user-shield"), " ", "role: ", comments$user_role, ", ",
      icon("calendar-alt"), " ", "date: ", comments$added_on,
      br(), br(), 
      comments$comment,
      "</div>",
      collapse = ""
    )
  )
}
```
becomes
```{r, eval=FALSE}
showComments <- function(pkg_name, comment_type){
  if (length(pkg_name) == 0)
    return("")
  
  ifelse(
    length(comments$user_name) == 0, 
    "No comments",
    paste0(
      "<div class='well'>",
      icon("user-tie"), " ", "user: ", comments$user_name, ", ", 
      icon("user-shield"), " ", "role: ", comments$user_role, ", ",
      icon("calendar-alt"), " ", "date: ", comments$added_on,
      br(), br(), 
      comments$comment,
      "</div>",
      collapse = ""
    )
  )
}
```

**Comment by marlycormar** [comment]
@marlycormar I'll take of reviewing this PR. Thanks @Jeff-Thompson12!

**Comment by marlycormar** [comment]
Moved PR to: https://github.com/pharmaR/risk_assessment/pull/211 to add a call to req since couldn't add a commit to this one. Also fixed conflict.

**Pull request merged**
