### PR TITLE
Remove "all" button from Comm Metrics Graph

### LINKED ISSUE #87: Community Metrics: Get rid of "All" button
image

### PR DESCRIPTION
**Pull request by AARON-CLARK**
fixes #87 

image

### CODE REVIEW

**Review by Robert-Krajcik — CHANGES_REQUESTED** [review]
I can see the `all` button has been removed, but the two-year history looks odd.
This is package `tidyr` and I know its been around for more than a year.
image

**Comment by AARON-CLARK** [comment]
> I can see the `all` button has been removed, but the two-year history looks odd.
> This is package `tidyr` and I know its been around for more than a year.

Hi @Robert-Krajcik. My PR just allows the graph to display 2 years of history. I thought the SQL function needed to be changed in another PR to actually pull in more data, no? I could be wrong.

**Comment by AARON-CLARK** [comment]
Hi gang, This PR is ready for a second review. @Robert-Krajcik showed me how to query cran for downloads going back 2 years instead of 1. And I added in a few minor fixes so that the annual downloads is still correct and "last release" button shows includes the last red vertical line (when appropriate).

**Review by Robert-Krajcik — APPROVED** [review]
LGTM!

**Pull request merged**
