### PR TITLE
Created the metric and package_metrics tables, and removed the TestMetrics table

### PR DESCRIPTION
**Pull request by marlycormar**
## Major changes
- Created a table called `metric` to store metric information
- Created a table called `package_metrics` to store metric information per package
- Removed the `TestMetrics` table and moved the information on this table to `metric` and `package_metrics` accordingly

_Notes_: 
- The table `MaintenanceMetrics` hasn't been migrated to `metric` and `package_metrics`. Such change should be part of the next PR.
- The name `package_metrics` is not set in stone. I tried to portray that this is a one-to-many relationship (mmm although it will contain multiple packages). I'm open to suggestions =)

### CODE REVIEW

**Comment by Robert-Krajcik** [comment]
Hi @marlycormar 
I have created a branch prepare_db_for_weights
and loaded four packages
```{r, eval=FALSE}
> db_fun("select id, name, version from package")
  id  name version
1  1    gt   0.2.2
2  2 rvest   0.3.6
3  3 tidyr   1.1.2
4  4 dplyr   1.0.2
```
From what I can see, the metric table has been initialized OK.
in dbupload.R, line 192
Should we be returning a list or just a single value?
Right now it returns
```{r, eval=FALSE}
> riskmetric_assess$covr_coverage[1]
<list_of<pkg_metric>[1]>
[[1]]
[1] NA
attr(,"class")
[1] "pkg_metric_na" "pkg_metric"    "logical"   
```
instead of perhaps
```{r, eval=FALSE}
> riskmetric_assess$covr_coverage[[1]][1]
[1] NA
```

**Comment by marlycormar** [comment]
Definitely @Robert-Krajcik! Making the change now...

**Review by Robert-Krajcik — APPROVED** [review]
Looks Good to Me!

**Comment by Robert-Krajcik** [comment]
I assume we are updating `description` in the `metric` table at a later time? @marlycormar

**Comment by marlycormar** [comment]
> I assume we are updating `description` in the `metric` table at a later time? @marlycormar

Yes, maybe we can even find a smart way of saving all the info needed to display the infoboxes.

**Pull request merged**
