### PR TITLE
managing user ids and passwords vignette

### PR DESCRIPTION
**Pull request by Robert-Krajcik**
This creates a vignette about managing user IDs and passwords

### CODE REVIEW

**Comment by Robert-Krajcik** [comment]
This is part of issue #147

**Comment by marlycormar** [comment]
Hi @Robert-Krajcik, I am reviewing this vignette now! I have moved all the vignettes to the `docs` folder in preparation for the live documentation site. You'll need to pull before making any more changes.

**Comment by Robert-Krajcik** [comment]
Thanks for the updates, @marlycormar.
I might have a few more small stylistic changes on this one.
Note Peter Parker, Jessica Drew and Miles Morales are characters from Spiderman/Spiderwoman movies.

**Review by AARON-CLARK — APPROVED** [review]
LGTM

**Comment by marlycormar** [comment]
Hi @Robert-Krajcik  and @AARON-CLARK, I reviewed the PR and included minor changes.

In addition, I noticed that in the pop up that appears when adding new users, there are some fields that are filled for default for me but not for Robert. Please let me know which behavior you see so that we can update the documentation accordingly.

When adding a new user:
- the start and expire date appear filled out by default, and
- the admin checkbox appears clicked by default.

Is this the same for you?

**Comment by marlycormar** [comment]
Thanks @AARON-CLARK !

**Comment by AARON-CLARK** [comment]
Fixed all remaining requested changes, so I'll go ahead and merge this PR.

image

**Pull request merged**
