### PR TITLE
initialize metric table dynamically using pkg_assess()

### PR DESCRIPTION
**Pull request by Robert-Krajcik**
Instead of doing this manually
```{r, eval=FALSE}
INSERT INTO metric (name, description, class, weight) values 
('package_has_vignettes', '', 'maintenance', 1),
('news_is_current', '', 'maintenance', 1),
('has_bug_reports', '', 'maintenance', 1),
('package_has_website', '', 'maintenance', 1),
('news_is_current', '', 'maintenance', 1),
('has_a_package_maintainer', '', 'maintenance', 1),
('source_code_is_public', '', 'maintenance', 1),
('exported_objects_with_documentation', '', 'maintenance', 1),
('status_of_last_30_reported_bugs', '', 'maintenance', 1),
('covr_coverage', '', 'test', 1);
```
This code is built for you dynamically and any new metrics are easily accommodated:
```{r, eval=FALSE}
INSERT INTO metric (name, description, class, weight) values
('news_current','NEWS file contains entry for current version number','maintenance',1),
('has_vignettes','number of discovered vignettes files','maintenance',1),
('has_bug_reports_url','presence of a bug reports url in repository','maintenance',1),
('bugs_status','vector indicating whether BugReports status is closed','maintenance',1),
('export_help','exported objects have documentation','maintenance',1),
('has_website','a vector of associated website urls','maintenance',1),
('has_maintainer','a vector of associated maintainers','maintenance',1),
('has_news','number of discovered NEWS files','maintenance',1),
('has_source_control','a vector of associated source control urls','maintenance',1),
('covr_coverage','Package unit test coverage','test',1)
```

### CODE REVIEW

**Comment by Robert-Krajcik** [comment]
With the last round of updates, @marlycormar 
I won't need to read a .csv file at all.
We now have two sets of labels, one from pkg_assess() and one from pkg_score()

**Comment by Robert-Krajcik** [comment]
Hi @marlycormar 
This PR is ready for review
The metric sql table definition is changed from
```{r, eval=FALSE}
CREATE TABLE IF NOT EXISTS metric(
   id           INTEGER PRIMARY KEY AUTOINCREMENT,
   name         CHAR, 
   description  CHAR,
   class        CHAR, /*class = maintenance or test*/
   weight       REAL
);
```
to
```{r, eval=FALSE}
CREATE TABLE IF NOT EXISTS metric(
   id           INTEGER PRIMARY KEY AUTOINCREMENT,
   name         CHAR, 
   as_label     CHAR, /* label from pkg_assess() */
   sc_descr     CHAR, /* label from pkg_score()  */
   is_thumb     INT,  /* SQLite does not have a separate Boolean storage class*/
   class        CHAR, /*class = maintenance or test*/
   weight       REAL
);
```
and is dynamically initialized whenever create_db() in utils.R is run
This gives me everything I need to do maintentance metrics reporting without using a .csv file

**Comment by Robert-Krajcik** [comment]
Hi @marlycormar 
The changes I made today will have the metric table look like this:

image

I added a tbl in the part of the create_db function so we could keep the maintenance metrics reporting look the same as before.
As I think about this, maybe the part of this function that initializes the metric table should be it's own function.

**Comment by AARON-CLARK** [comment]
Converting to draft since this PR was intended for `master`

**Pull request closed without merging**
