### PR TITLE
Fix admins view

### PR DESCRIPTION
**Pull request by Robert-Krajcik**
This is what I have so far, @marlycormar

### CODE REVIEW

**Comment by Robert-Krajcik** [comment]
I have settled on this piece of code, and removed the `<<-` assignment
```{r, eval=FALSE}
    save <- reactiveValues(data=NULL)
    
    curr_new_wts <- eventReactive(input$update_weight, {
      if (is_empty(input$update_weight)) {
        get_metric_weights() %>%
          mutate(weight = ifelse(name == "covr_coverage", 0, weight)) 
      } else {
          save$data %>%
          mutate(new_weight = ifelse(name == isolate(input$metric_name),
                                    isolate(input$metric_weight), new_weight))
      }
    }, ignoreNULL = FALSE)
    
    observeEvent(curr_new_wts(), {
      save$data <- isolate(curr_new_wts())
    })
```

**Comment by Robert-Krajcik** [comment]
Ready for your review, @marlycormar

**Comment by Robert-Krajcik** [comment]
Switching the reviewer to you @AARON-CLARK, since Marly is going to be OOO for a few days.

**Review by AARON-CLARK — CHANGES_REQUESTED** [review]
Hi Robert, things look good in this PR. However, there are a few things that still need to be fixed in order to get this "module" back to it's original glory (as it was on the `master` branch)... OR you could always kick them down the road to poor @Jeff-Thompson12's [Admin mode PR](https://github.com/pharmaR/risk_assessment/pull/204) too. Also, @Jeff-Thompson12, are you waiting on changes from this branch? 

This isn't an exhaustive list, but just a few things I noticed pretty quickly:

You can't exit this modal if you tried, lol. The "cancel" button doesn't dismiss the modal nor does clicking any where off screen/modal:
image

After you click `Re-calculate`, all the highlighted rows should lose the highlighting, and the current new weights become the current weights. Currently, if I log out and back in, I do see the new weights, so it's definitely saving them to the db... but the DT::datatable should be more reactive and update in real time.
image

**Comment by Robert-Krajcik** [comment]
Handing this one to @Jeff-Thompson12

**Pull request merged**
