### PR TITLE
Re-org utils files

### PR DESCRIPTION
**Pull request by AARON-CLARK**
This PR seeks to perform some general re-organizing of the package's infrastructure (specifically, with the utils files) to make development and testing easier.

### CODE REVIEW

**Review by Robert-Krajcik — COMMENTED** [review]
Hi @AARON-CLARK 
This arrangement will make it easier to maintain functions for sure.
We may want to update the roxygen2 tags, adding `#' @noRd` for internal (like startup) functions and perhaps
```{r, eval=FALSE}
#' @keywords internal
#' @export
```
for functions we don't want to be too visible

**Comment by AARON-CLARK** [comment]
hi @Robert-Krajcik, I forgot to update an Rd file after fixing a merge conflict. This branch is ready now. Thanks!

**Review by Jeff-Thompson12 — APPROVED** [review]
Everything LGTM

**Comment by Jeff-Thompson12** [comment]
> That sounds good to me @Robert-Krajcik. Let's have each developer add the appropriate tags in their `testthat` PRs since they'll be spending lots of time with the functions anyhow. If this PR looks good, please feel free to merge.

Or in a documentation specific PR.

**Pull request merged**
