### PR TITLE
sidebar remembers package/version after return from dashboard_screen

### PR DESCRIPTION
**Pull request by Robert-Krajcik**

### CODE REVIEW

**Review by AARON-CLARK — CHANGES_REQUESTED** [review]
Hi @Robert-Krajcik,

It looks like something fishy is going on still, so I requested changes on the PR.

See the following example: I've made a decision on the package `stringr`. We know this, because the comments and `submit` buttons are disabled here: 

image

We can confirm this when I navigate to the Database Overview screen:

image

However, when I navigate back to sidebar, the package name is retained, BUT it erroneously allows me to submit another comment or another decision!

image

**Comment by Robert-Krajcik** [comment]
Thanks for testing this so thouroughly, @AARON-CLARK 
I will take a look and see what else it needs to work properly.

**Comment by Robert-Krajcik** [comment]
This latest fix seems to work, @AARON-CLARK 
There were actually two observes going on, both trying to decide if they should enable/disable the decisions.
The updated code looks like this:
```{r, eval=FALSE}
# Disable/enable the comments depending package selected and no decision made yet.
observeEvent(list(input$select_pack, values$selected_pkg$decision), {
  req(input$select_pack)
  if (input$select_pack != "Select" && (is_empty(values$selected_pkg$decision) || values$selected_pkg$decision == "")) {
    enable("decision")
    enable("submit_decision")
    enable("overall_comment")
    enable("submit_overall_comment")

  } else{
    disable("decision")
    disable("submit_decision")
    disable("overall_comment")
    disable("submit_overall_comment")

  }
}, ignoreInit = TRUE)
```

**Comment by Robert-Krajcik** [comment]
In this code from master, two observes compete with each other.
The first one disables the widgets because a decision was made, and then the second enables them as the package name != Select
```{r, eval=FALSE)
# Disable/enable the comments depending on wether a decision has been made.
observe({
  req(values$selected_pkg$name)
  if (values$selected_pkg$decision != "") {
    # Disable all the decision-related choices.
    disable("decision")
    disable("submit_decision")
    disable("overall_comment")
    disable("submit_overall_comment")
  } else{
    enable("decision")
    enable("submit_decision")
    enable("overall_comment")
    enable("submit_overall_comment")
  }
})


observe({
  req(input$select_pack)
  if (input$select_pack == "Select") {
    disable("decision")
    disable("submit_decision")
    disable("overall_comment")
    disable("submit_overall_comment")
  } else{
    enable("decision")
    enable("submit_decision")
    enable("overall_comment")
    enable("submit_overall_comment")
  }
})
```

**Review by AARON-CLARK — APPROVED** [review]
LGTM!

**Pull request merged**
