### PR TITLE
Improve docx report

### PR DESCRIPTION
**Pull request by Jeff-Thompson12**
Some improvements to ReportDocx.Rmd.

### CODE REVIEW

**Comment by AARON-CLARK** [comment]
@Jeff-Thompson12, is this ready for review?

**Comment by Jeff-Thompson12** [comment]
@AARON-CLARK Yes

**Comment by Jeff-Thompson12** [comment]
I changed where the Rmd files were being ran because it made it "easier" to include the icons in the docx, but if the Rmd files need to be ran in a temporary directory I can modify the code to handle that.

**Review by AARON-CLARK — CHANGES_REQUESTED** [review]
This appears to work for me (locally). However, copying files to a temp dir is important when the app is deployed on a server (like shinyapps.io), so I think that code needs to be brought back. Here is a snippet from Wickham's "Mastering Shiny" book:

image

**Review by AARON-CLARK — APPROVED** [review]
LG

**Pull request merged**
