### PR TITLE
fix downloads plot for community usage metrics

### PR DESCRIPTION
**Pull request by Robert-Krajcik**
addresses issue #171

### CODE REVIEW

**Comment by Robert-Krajcik** [comment]
before:
image

after:
image

**Comment by marlycormar** [comment]
Hi @Robert-Krajcik, the plot is looking great!

Some comments:
- The lower bar (where one could select a time frame) no longer shows.
- The labels 6 mo, 1 yr, etc. overlap for me with the title (I am using my laptop to test it, maybe you tested it on a wider screen?).

**Comment by Robert-Krajcik** [comment]
All set for your review, @marlycormar

**Comment by AARON-CLARK** [comment]
Converting to 'draft' until all issues in #171 are complete.

**Comment by Robert-Krajcik** [comment]
Yeah I noticed function `insert_community_metrics_to_db` is reading `https://cran.r-project.org/src/contrib/Archive`
which unfortunately seems to be always one release behind.
I'll do google search to see if there is some other way to get  package release history.

**Comment by AARON-CLARK** [comment]
> I'll do google search to see if there is some other way to get package release history.

No need @Robert-Krajcik ! I'm working on a patch that actually re-uses existing code in the app to get the latest package info. I'll push the commit(s) shortly.

**Comment by AARON-CLARK** [comment]
Hi @marlycormar & @Robert-Krajcik. This PR has been updated to tackle all the issues mentioned in #171 and is ready for your review!

**Comment by marlycormar** [comment]
Hi @AARON-CLARK, maybe is my browser that is caching, but the font family and color haven't updated (i.e., they don't watch those of the rest of the app).

**Comment by AARON-CLARK** [comment]
Good catch @marlycormar. I changed the plot colors to match the pink and blue from the bootstrap theme, but I noticed plotly renders them both slightly darker... but I think that's a good thing since those shades are pretty light for a plot. Please see for yourself!

image

**Comment by marlycormar** [comment]
I think that's ok! They look mostly the same. 

The font of the plot is:

``
font-family: "Nunito Sans", -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol";
``

**Comment by AARON-CLARK** [comment]
Hi @marlycormar or @Robert-Krajcik, I matched the app's font family and adjusted the margin around the plot's title so that it doesn't collide with other plot elements when the window/screen is resized. I also made the title size a little more prominent in size and all caps. Those were my last to-do items for this PR. What do you think?

image

**Comment by marlycormar** [comment]
Hi @AARON, thanks for making these changes!! I was trying to set other font properties to make it match perfectly with the rest of the headings, but couldn't get it to work within Plotly. I added a css instead.

Let me know what you think. If it looks ok, please feel free to merge it.

**Pull request merged**
