### PR TITLE
Fix card scrolls & size - text is hidden

### PR DESCRIPTION
**Pull request by marlycormar**
Removed card scrolls. 

_Note:_ The cards (by bootstrap design) have a horizontal line that overflows from the cards. I think it doesn't look bad, but let me know if this is not the case to find a way to change it.

### CODE REVIEW

**Comment by marlycormar** [comment]
Closes issue #198.

**Review by AARON-CLARK — CHANGES_REQUESTED** [review]
Hi @marlycormar, thanks for the PR! The good news is the scroll bars are gone! But some other elements of the cards are getting pushed around. See this example when "dplyr" is selected:

image

**Comment by AARON-CLARK** [comment]
@marlycormar, follow up to post above: I made sure my browser resolution was set to 100%. It must be because the URLs are wrapping to three lines instead of two. Can we truncate them slightly more? Or make the font waaaay smaller for URLs and emails? It is quite large right now.

**Comment by marlycormar** [comment]
Thanks for reviewing this PR!

I'll cut the url string a bit more and make a few other changes to make it look better.

**Comment by Robert-Krajcik** [comment]
Por supuesto, @marlycormar

**Comment by Robert-Krajcik** [comment]
I'm using google chrome

**Comment by AARON-CLARK** [comment]
@marlycormar, can you give this another look this week? I think you were really close the last time I reviewed the code:

> It must be because the URLs are wrapping to three lines instead of two. Can we truncate them slightly more? Or make the font waaaay smaller for URLs and emails? It is quite large right now.

**Comment by AARON-CLARK** [comment]
closed with improved PR #296

**Pull request closed without merging**
