### PR TITLE
Update readme

### PR DESCRIPTION
**Pull request by marlycormar**
Partially address #147.

**PR Overview**
- Introduce the app
- Explain how the app extends riskmetric
- Briefly explain the reach of admins
- Present our approach to validation (i.e., set expectations)
- Add Aaron and Robert as maintainers
- Refer to License file instead of writing the license on the Readme
- Remove dangling LICENSE file

_Need:_ a link to the documentation once it is finalized.

### CODE REVIEW

**Review by AARON-CLARK — APPROVED** [review]
Great start! I just added a hyperlink to my personal website and that's it for now.

**Comment by marlycormar** [comment]
Sounds good @AARON-CLARK. Let's discuss the Readme on today's meeting.

**Review by Robert-Krajcik — APPROVED** [review]
Looks good to me!

**Comment by marlycormar** [comment]
Ready for your review @Robert-Krajcik and @AARON-CLARK!

**Review by AARON-CLARK — APPROVED** [review]
LGTM!

**Pull request merged**
