### PR TITLE
Deploy shinyapp

### PR DESCRIPTION
**Pull request by Robert-Krajcik**
Addresses issue #213

### CODE REVIEW

**Comment by Robert-Krajcik** [comment]
Two additional things need to be done:

1. delete loggit.json and credentials.sqlite (optionally delete database.sqlite)
2. `library(rsconnect)` and `deployApp(account = "your-account")`

**Comment by Robert-Krajcik** [comment]
going to do more testing on this.

**Comment by Robert-Krajcik** [comment]
This might be helpful as well
https://docs.rstudio.com/shinyapps.io/index.html

**Comment by Robert-Krajcik** [comment]
One oddity I have noticed, after finally getting the app to deploy,
was that community usage metrics was not being loaded for some reason.
Yet the upload package part seems to run just fine.

image

**Comment by Robert-Krajcik** [comment]
Finally got .gitignore to ignore rsconnect folder

**Comment by Jeff-Thompson12** [comment]
So I just discovered that `shinymanager::create_db` is hard coded to create an SQLite database, and `shinymanager` is built around SQLite connections. This seems to me to be a big problem with being able to deploy the application. Once deployed the credentials database will not be able to be updated and retain the updated information. You would have to have a "finalized" credentials database at deployment.

**Comment by Robert-Krajcik** [comment]
I am able to get this to deploy, using my account (robert-krajcik)
However, I am unable to get it to upload a .csv file with new package information.

image

**Comment by Robert-Krajcik** [comment]
Oh wow, I actually got it to upload a couple of new packages!

image

**Comment by AARON-CLARK** [comment]
Regarding the SQLite stuff, I think it's important to keep in mind that our shinyapps.io deployment is purely for demonstration purposes, and most companies don't use shinyapps.io to deploy an app internally (right?). Instead their probably using shinyserver or RSConnect, which allows persistent storage. So, at the end of the day, it stinks that we won't be able to demo all the `shinymanager` features, but having a sample SQLites db pre-loaded for shinyapps.io works just fine for now.

I was hoping to have an RSConnect demo prepared for our meeting today to prove that the SQLite stuff works, but it looks like this branch has the following error:

image

Any thoughts @Robert-Krajcik or @Jeff-Thompson12?

**Comment by Robert-Krajcik** [comment]
Hi @AARON-CLARK 
I was just using this branch last week.
Why would `keyring_create()` think that password was an unused argument?
I'll take a look right now.

**Comment by Robert-Krajcik** [comment]
FYI,
Regarding the question Can SQLite be used for multiple users?

> Yes SQLite can support multiple users at once. It does however lock the whole database when writing, so if you have lots of concurrent writes it is not the database you want (usually the time the database is locked is a few milliseconds - so for most uses this does not matter).

[Can SQLite be used for multiple users?](https://stackoverflow.com/questions/5102027/can-sqlite-support-multiple-users)

So it appears we can have multiple users adding package information or multiple admins adding users.

**Comment by marlycormar** [comment]
Closing this PR in favor of branch [shinyapps](https://github.com/pharmaR/risk_assessment/tree/shinyapps).

**Pull request closed without merging**
