### PR TITLE
Fix version and other changes

### PR DESCRIPTION
**Pull request by marlycormar**
Changes on this PR:

- Fixed version number that appeared with commas instead of dots.
- Made uploadPackage, maitenanceMetrics, communityMetrics, reportPreview, modules.
- Fixed database view table not updating.
- Added missing community metrics from reportPreview.
- Fix html report download on the reportPrevew tab.
- Removed dangling `values` reactive.
- Improved function to uploadPackage (merged two loops).
- Removed manual R files sourcing as this is already done by default.
- Improve code by sharing information that is commonly used (for instance, comments on the maintenance metrics tab are read once, and used throughout the app).
- Otherssss

Items that need attention (I can address them in a different PR):
- Mimic reportHtml.Rmd to create a docx report.
- The reports on the database view error out when creating.

### CODE REVIEW

**Comment by AARON-CLARK** [comment]
Hi @marlycormar, I haven't tested much on this branch. But I did test the introjs guide for the upload packages tab and it's no longer working as it once was on `dev`. Happy to help more on Monday but just wanted to bring that to your attention in case you were planning to work on RAA this weekend. Cheers!

**Comment by marlycormar** [comment]
Thanks @AARON-CLARK! I am indeed planing to work on RAA this weekend. I didn't test introJS, but I guess that since it was not working on dev (when we tested it on Friday), it should not be working here as well.

**Comment by AARON-CLARK** [comment]
Hi @marlycormar, don't work too hard!

Yeah, I don't know what happened during Friday's walk through. We certainly observed some strange behavior, but I tested it on `dev` this morning and everything was working as expected - no issues. Feel free to re-test the `dev` branch for yourself to confirm.

**Comment by AARON-CLARK** [comment]
Wow, just peaked at the changes on this PR. Seems like a big one @marlycormar! I'm afraid to work on any other issues until this get's pushed through (to avoid re-work). Let me know when you need a reviewer!

**Comment by marlycormar** [comment]
hahaha, yes! so sorry about that 😬

I'll try to make a final push by EOD, so that it can be reviewed starting tomorrow.

**Comment by marlycormar** [comment]
Hi @AARON-CLARK and @Robert-Krajcik, this PR is finally ready for review. There are some items that I didn't get a chance to touch, but I promised you not to hold the PR any longer.

I apologize for the many changes in this PR, but as I tried to fix one thing, I realized others needed fixing first. For instance, to fix the reportPreview tab, I had to add the community metrics grid. But the grid was hardcoded for maintenance metrics. So I had to make the metricsGrid more generic, then fix the community metrics tab, and then report. After that, there was a lot of code duplication since the community metrics tab wasn't a module, so I made the community metrics a module before proceeding. And then... the story goes on!!

Please test it carefully!

**Comment by Jeff-Thompson12** [comment]
I will close PR #179 in that case since it made the metricsGrid module more general as well.

**Comment by Robert-Krajcik** [comment]
Vaya @marlycormar, this PR is gigantesco.
We have been holding off on making any other changes until this one gets merged.
We should re-review any outstanding issues after this and update the "Potential Features" issue #176

**Review by AARON-CLARK — CHANGES_REQUESTED** [review]
Hi @marlycormar, I certainly haven't combed through every change in this PR, but as previously stated: the introjs help buttons do not work like they do on `dev`. This would be a good first issue to fix while you're waiting for the full review from myself and @Robert-Krajcik! I'm bouncing around to a couple different projects today so I may not get to my review till tomorrow.

image

**Comment by Robert-Krajcik** [comment]
Introjs actually seems to be working @AARON-CLARK 

The only thing I noticed was maybe moving this one closer to the sample dataset.
image

**Comment by AARON-CLARK** [comment]
@Robert-Krajcik, it's pretty fragmented for me. And the fact that it's not closer to the "View Sample Dataset" button is proof that it's not working. The pop-up is supposed to display right next to each UI element. If introjs can't find the UI element, then the box appears in the middle of the screen, which is what you've displayed.

**Comment by Robert-Krajcik** [comment]
Allowing packages like "stanly" and "samplesizeCMH" cause the app to blow up.
```{r, eval=FALSE}
{"timestamp": "2022-03-09T12:26:06-0500", "log_lvl": "INFO", "log_msg": "User PeterParker signed on as admin"}
Warning in min(year) : no non-missing arguments to min; returning Inf
Warning in min(month) : no non-missing arguments to min; returning Inf
Warning: Error in if: argument is of length zero
  1: runApp
Warning: Error in if: argument is of length zero
  1: runApp
```
This might be due to dbupload.R using 
`'https://cran.r-project.org/src/contrib/Archive/{pkg_name}'`
Which is an easy way to collect version history for community usage metrics

**Comment by Robert-Krajcik** [comment]
I'm looking at it now @marlycormar

**Comment by marlycormar** [comment]
Gracias!! @Robert-Krajcik

**Review by Robert-Krajcik — APPROVED** [review]
This PR addresses `muchas cosas`, but not everything.
There are some outstanding issues listed above, but these can be addressed in other PRs.
What you have here looks good and it runs.  Let's go with it. `Sigamos adelante`

**Comment by Robert-Krajcik** [comment]
The 1st and 3rd modals of introjs don't quite line up
image
image

The rest look fine.  This can be a subsequent PR

**Comment by marlycormar** [comment]
Perfect! Mergiendo....

**Pull request merged**
