### PR TITLE
Improve database feedback

### PR DESCRIPTION
**Pull request by marlycormar**
Addresses issue #122

### CODE REVIEW

**Comment by Robert-Krajcik** [comment]
Yeah, this is what I was thinking, @marlycormar 

`The dbSendStatement() method only submits and synchronously executes the SQL data manipulation statement (e.g., UPDATE, DELETE, INSERT INTO, DROP TABLE, ...) to the database engine. To query the number of affected rows, call dbGetRowsAffected() on the returned result object. You must also call dbClearResult() after that. `

We could log a message when 0 rows were affected (something didn't go well with the statement)

**Review by Robert-Krajcik — CHANGES_REQUESTED** [review]
I think this needs some work, @marlycormar 

For example, if I type in
`db_query <- db_fun("select * from Comments where commentztype == 'o'")`

It returns
```{r, eval=FALSE}
{"timestamp": "2021-05-26T16:21:47-0400", "log_lvl": "ERROR", "log_msg": "db_fun error:  Error: no such column: commentztype__LF__"}
{"timestamp": "2021-05-26T16:21:47-0400", "log_lvl": "ERROR", "log_msg": "list(message = __DBLQUOTE__no such column: commentztype__DBLQUOTE____COMMA__ call = NULL__COMMA__ cppstack = NULL)"}
Error in stop(err) : 
  list(message = "no such column: commentztype", call = NULL, cppstack = NULL)
Called from: base::stop(unlist(args), call. = call., domain = domain)
Browse[1]> 
```
The message gets logged twice and you get dumped into Browse
In my opionion, the stop() isn't needed.

It doesn't catch this one, where the table and variable name are correct but not the parameter.
`db_query <- db_fun("select * from Comments where comment_type == 'x'")`

Now if we redesign the function like this:
```{r, eval=FALSE}
db_fun <- function(query){
  errFlag <- FALSE
  con <- dbConnect(RSQLite::SQLite(), db_name)
  tryCatch(
  expr = {
    rs <- dbSendQuery(con, query)
  },
  warning = function(warn) {
    message <- paste0("db_fun warning:\n",query,"\nresulted in\n",warn)
    message(message, .loggit = FALSE)
    loggit("WARN", message)
    errFlag <<- TRUE
  },
  error = function(err) {
    message <- paste0("db_fun error:\n",query,"\nresulted in\n",err)
    message(message, .loggit = FALSE)
    loggit("ERROR", message)
    dbDisconnect(con)
    errFlag <<- TRUE
  },
  finally ={
    if (errFlag) return(NULL) 
  })
  
  dat <- dbFetch(rs)
  dbClearResult(rs)
  if (nrow(dat) == 0) message(paste0("No rows were returned from db_fun query\n",query))
  dbDisconnect(con)
  return(dat)
}
```
It handles this condition nicely:
> db_query <- db_fun("select * from Comments where commentztype == 'o'")
db_fun error:
select * from Comments where commentztype == 'o'
resulted in
Error: no such column: commentztype

`{"timestamp": "2021-05-26T16:45:23-0400", "log_lvl": "ERROR", "log_msg": "db_fun error:__LF__select * from Comments where commentztype == 'o'__LF__resulted in__LF__Error: no such column: commentztype__LF__"}`

And even handles this one.
> db_query <- db_fun("select * from Comments where comment_type == 'x'")
`{"timestamp": "2021-05-26T16:48:15-0400", "log_lvl": "INFO", "log_msg": "No rows were returned from db_fun query__LF__select * from Comments where comment_type == 'x'"}`

No rows were returned from db_fun query
select * from Comments where comment_type == 'x'

**Comment by marlycormar** [comment]
Hey @Robert-Krajcik, please let me know if the functions are ready to be tested (maybe in a separate PR?).

**Comment by marlycormar** [comment]
Removing this PR in light of PR #131 .

**Pull request closed without merging**
